[project]
name = "mcp-server-gravitino"
version = "0.1.0"
description = "MCP server providing Gravitino APIs"
authors = [
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
keywords = ["mcp", "fastmcp", "Gravitino", "metadata", "integration"]
dependencies = [
    "fastmcp>=2.2.7",
    "httpx>=0.28.1",
    "pydantic-settings>=2.8.1",
]
py_modules = ["mcp_server_gravitino"]

[project.urls]
Homepage = "https://github.com/datastrato/mcp-server-gravitino"
Repository = "https://github.com/datastrato/mcp-server-gravitino"
Documentation = "https://github.com/datastrato/mcp-server-gravitino#readme"
"Bug Tracker" = "https://github.com/datastrato/mcp-server-gravitino/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
    "mcp_server_gravitino/**/*.py",
    "README.md",
    "LICENSE",
]
exclude = [
    "**/__pycache__",
    "**/*.py[cod]",
    "**/*.so",
]
[tool.hatch.build.targets.wheel]
packages = ["mcp_server_gravitino"]


[project.optional-dependencies]
dev = [
    "build>=1.2.2.post1",
    "ruff>=0.11.3",
    "twine>=6.1.0",
    "pytest>=8.2.0",
    "pytest-asyncio>=0.23.0"
]

[tool.ruff]
line-length = 120
target-version = "py310"
select = [
    "I",  # isort
]

[tool.pytest.ini_options]
minversion = "8.0" # Minimum pytest version.
addopts = "-ra" # Show summary info and all type of tests.
testpaths = [
    "tests",
]